const defaultMenuItems=[
 {id:1,name:'Steamed Momos',category:'momos',description:'Soft pockets, bold filling, JUT chilli dip.',price:149,tag:'Bestseller',veg:true,localImage:'',image:'https://images.unsplash.com/photo-1625220194771-7ebdea0b70b9?auto=format&fit=crop&w=800&q=85'},
 {id:2,name:'Grilled Sandwich',category:'sandwiches',description:'Golden toast, molten cheese, secret sauce.',price:129,tag:'Hot off grill',veg:true,localImage:'assets/IMG-20260918-WA0007.jpg.jpeg',image:'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=800&q=85'},
 {id:3,name:'Crispy Snacks',category:'snacks',description:'Golden crunch with a smoky JUT masala dip.',price:99,tag:'Crispy',veg:true,localImage:'assets/IMG-20260827-WA0002.jpg.jpeg',image:'https://images.unsplash.com/photo-1551754655-cd27e38d2076?auto=format&fit=crop&w=800&q=85'},
 {id:4,name:'JUT Combo',category:'combos',description:'Momos, sandwich bites, fries and a drink.',price:299,tag:'Good deal',veg:true,localImage:'assets/IMG-20260827-WA0005.jpg.jpeg',image:'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=85'}
];
let menuItems=(()=>{try{const saved=JSON.parse(localStorage.getItem('jutMenuItems'));return Array.isArray(saved)&&saved.length?saved:defaultMenuItems}catch(error){return defaultMenuItems}})();
let cart=[];
const $=s=>document.querySelector(s);
const foodGrid=$('#foodGrid');
const ownerPanel=$('#ownerPanel');
$('#currentLocation').textContent=JUT_CONFIG.currentLocation;
$('#todayHours').textContent=JUT_CONFIG.todayHours;
document.querySelector('.map-status').innerHTML='<span class="pulse-dot"></span> Demo location';
document.querySelector('.button-dark').href=JUT_CONFIG.directionsUrl||`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(JUT_CONFIG.directionsQuery)}`;
document.querySelector('a[href^="tel:"]').href=`tel:+91${JUT_CONFIG.contactNumber}`;
document.querySelector('.footer-links > div:nth-child(2) a:last-child').href=`https://wa.me/${JUT_CONFIG.whatsappNumber}?text=${encodeURIComponent('Namaste JUT! I would like to know today\'s menu, location and ordering details.')}`;
function renderMenu(filter='all'){
 const items=filter==='all'?menuItems:menuItems.filter(item=>item.category===filter);
 foodGrid.innerHTML=items.map((item,index)=>`<article class="food-card" data-tilt style="animation-delay:${index*70}ms"><div class="food-image" style="background-image:url('${item.localImage}'),url('${item.image}')"><span class="food-tag">${item.tag}</span>${item.veg?'<span class="veg" title="Vegetarian"></span>':''}</div><div class="food-content"><h3>${item.name}</h3><p>${item.description}</p><div class="food-bottom"><strong class="price">₹${item.price}</strong><button class="add-button" data-add="${item.id}" aria-label="Add ${item.name} to cart">+</button></div></div></article>`).join('');
 foodGrid.querySelectorAll('[data-add]').forEach(button=>button.addEventListener('click',()=>addToCart(Number(button.dataset.add))));
 foodGrid.querySelectorAll('[data-tilt]').forEach(addTilt);
}
function addToCart(id){const existing=cart.find(item=>item.id===id);if(existing)existing.quantity++;else cart.push({id,quantity:1});updateCart();openCart();}
function updateCart(){
 const count=cart.reduce((total,item)=>total+item.quantity,0);$('#cartCount').textContent=count;
 const total=cart.reduce((sum,line)=>{const item=menuItems.find(menuItem=>menuItem.id===line.id);return sum+item.price*line.quantity},0);$('#cartTotal').textContent=`₹${total}`;
 if(!cart.length){$('#cartItems').innerHTML='<div class="empty-cart"><span>✦</span><p>Your cart is waiting<br>for something tasty.</p><a href="#menu" id="browseMenu">Browse the menu ↗</a></div>';$('#browseMenu').addEventListener('click',closeCart);}
 else{$('#cartItems').innerHTML=cart.map(line=>{const item=menuItems.find(menuItem=>menuItem.id===line.id);return `<div class="cart-row"><div class="cart-thumb" style="background-image:url('${item.localImage}'),url('${item.image}')"></div><div class="cart-row-info"><h4>${item.name}</h4><small>₹${item.price} each</small><div class="quantity-controls"><button data-quantity="${item.id}" data-change="-1" aria-label="Decrease quantity">−</button><span>${line.quantity}</span><button data-quantity="${item.id}" data-change="1" aria-label="Increase quantity">+</button></div></div><strong class="cart-row-price">₹${item.price*line.quantity}</strong></div>`}).join('');$('#cartItems').querySelectorAll('[data-quantity]').forEach(button=>button.addEventListener('click',()=>changeQuantity(Number(button.dataset.quantity),Number(button.dataset.change))));}
 const lines=cart.map(line=>{const item=menuItems.find(menuItem=>menuItem.id===line.id);return `• ${item.name} x ${line.quantity}`}).join('\n');const message=cart.length?`Namaste JUT! I would like to place an order.\n\n${lines}\n\nEstimated total: ₹${total}\nPickup location: ${JUT_CONFIG.currentLocation}\nName: ____\nPreferred time: ____\n\nPlease confirm availability. Thank you!`:`Namaste JUT! I would like to know today's menu, location and ordering details.`;$('#whatsappButton').href=`https://wa.me/${JUT_CONFIG.whatsappNumber}?text=${encodeURIComponent(message)}`;
}
function changeQuantity(id,change){const line=cart.find(item=>item.id===id);if(!line)return;line.quantity+=change;if(line.quantity<=0)cart=cart.filter(item=>item.id!==id);updateCart();}
function openCart(){$('#cartDrawer').classList.add('open');$('#cartDrawer').setAttribute('aria-hidden','false');$('#cartOverlay').classList.add('visible');document.body.style.overflow='hidden';}
function closeCart(){$('#cartDrawer').classList.remove('open');$('#cartDrawer').setAttribute('aria-hidden','true');$('#cartOverlay').classList.remove('visible');document.body.style.overflow='';}
function escapeHTML(value){return String(value??'').replace(/[&<>'"]/g,character=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[character]))}
function renderOwnerMenu(){
 $('#ownerMenuRows').innerHTML=menuItems.map((item,index)=>`<div class="owner-row" data-owner-index="${index}"><div class="owner-row-top"><strong>Item ${index+1}</strong><button type="button" class="owner-row-remove" data-remove-item="${index}">Remove</button></div><label>Name<input data-owner-field="name" value="${escapeHTML(item.name)}" required></label><label>Price<input data-owner-field="price" type="number" min="0" value="${item.price}" required></label><label>Description<input data-owner-field="description" value="${escapeHTML(item.description)}" required></label><label>Image URL or local path<input data-owner-field="image" value="${escapeHTML(item.localImage||item.image)}"></label></div>`).join('');
 $('#ownerMenuRows').querySelectorAll('[data-remove-item]').forEach(button=>button.addEventListener('click',()=>{if(menuItems.length===1)return;menuItems.splice(Number(button.dataset.removeItem),1);renderOwnerMenu()}));
}
function openOwner(){renderOwnerMenu();document.querySelector('[name="whatsappNumber"]').value=JUT_CONFIG.whatsappNumber;document.querySelector('[name="currentLocation"]').value=JUT_CONFIG.currentLocation;document.querySelector('[name="todayHours"]').value=JUT_CONFIG.todayHours;document.querySelector('[name="directionsQuery"]').value=JUT_CONFIG.directionsQuery;ownerPanel.classList.add('open');ownerPanel.setAttribute('aria-hidden','false');$('#ownerOverlay').classList.add('visible');document.body.style.overflow='hidden';}
function closeOwner(){ownerPanel.classList.remove('open');ownerPanel.setAttribute('aria-hidden','true');$('#ownerOverlay').classList.remove('visible');document.body.style.overflow='';}
function saveOwner(event){event.preventDefault();const formData=new FormData(event.currentTarget);const whatsappNumber=formData.get('whatsappNumber').trim();const currentLocation=formData.get('currentLocation').trim();const todayHours=formData.get('todayHours').trim();const directionsQuery=formData.get('directionsQuery').trim();if(whatsappNumber)JUT_CONFIG.whatsappNumber=whatsappNumber;if(currentLocation)JUT_CONFIG.currentLocation=currentLocation;if(todayHours)JUT_CONFIG.todayHours=todayHours;if(directionsQuery)JUT_CONFIG.directionsQuery=directionsQuery;menuItems=[...document.querySelectorAll('.owner-row')].map((row,index)=>{const get=name=>row.querySelector(`[data-owner-field="${name}"]`).value.trim();const previous=menuItems[index]||{};const image=get('image');return {...previous,id:previous.id||Date.now()+index,name:get('name'),description:get('description'),price:Math.max(0,Number(get('price'))||0),localImage:image,image:image}});localStorage.setItem('jutConfig',JSON.stringify(JUT_CONFIG));localStorage.setItem('jutMenuItems',JSON.stringify(menuItems));$('#currentLocation').textContent=JUT_CONFIG.currentLocation;$('#todayHours').textContent=JUT_CONFIG.todayHours;document.querySelector('.button-dark').href=JUT_CONFIG.directionsUrl||`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(JUT_CONFIG.directionsQuery)}`;renderMenu(document.querySelector('.filter.active').dataset.filter);updateCart();$('#ownerStatus').textContent='Saved. Your public page is updated.';setTimeout(()=>$('#ownerStatus').textContent='',3000);}
function resetOwner(){localStorage.removeItem('jutConfig');localStorage.removeItem('jutMenuItems');location.reload();}
renderMenu();updateCart();
document.querySelectorAll('.filter').forEach(button=>button.addEventListener('click',()=>{document.querySelector('.filter.active').classList.remove('active');button.classList.add('active');renderMenu(button.dataset.filter);}));
$('#floatingCart').addEventListener('click',openCart);$('#closeCart').addEventListener('click',closeCart);$('#cartOverlay').addEventListener('click',closeCart);
$('#ownerOpen').addEventListener('click',openOwner);$('#ownerClose').addEventListener('click',closeOwner);$('#ownerOverlay').addEventListener('click',closeOwner);$('#ownerForm').addEventListener('submit',saveOwner);$('#ownerReset').addEventListener('click',resetOwner);$('#ownerAddItem').addEventListener('click',()=>{menuItems.push({id:Date.now(),name:'New menu item',category:'snacks',description:'Add a description for this item.',price:0,tag:'New',veg:true,localImage:'',image:'https://images.unsplash.com/photo-1551754655-cd27e38d2076?auto=format&fit=crop&w=800&q=85'});renderOwnerMenu()});
$('#menuToggle').addEventListener('click',()=>{const isOpen=$('#navLinks').classList.toggle('open');$('#menuToggle').setAttribute('aria-expanded',isOpen);});
document.querySelectorAll('.nav-links a').forEach(link=>link.addEventListener('click',()=>{$('#navLinks').classList.remove('open');$('#menuToggle').setAttribute('aria-expanded','false');}));
function updateScrollEffects(){const maxScroll=document.documentElement.scrollHeight-window.innerHeight;$('#scrollProgress').style.transform=`scaleX(${maxScroll?window.scrollY/maxScroll:0})`;$('.site-header').classList.toggle('scrolled',window.scrollY>30);document.querySelectorAll('[data-parallax]').forEach(element=>{const speed=Number(element.dataset.parallax);const bounds=element.getBoundingClientRect();const offset=(window.innerHeight/2-(bounds.top+bounds.height/2))*speed;element.style.backgroundPosition=`center calc(50% + ${offset}px)`})}
window.addEventListener('scroll',updateScrollEffects,{passive:true});
window.addEventListener('resize',updateScrollEffects,{passive:true});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
function addTilt(card){card.addEventListener('pointermove',event=>{if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const bounds=card.getBoundingClientRect();const rotateY=((event.clientX-bounds.left)/bounds.width-.5)*7;const rotateX=-((event.clientY-bounds.top)/bounds.height-.5)*7;card.style.transform=`perspective(700px) rotateX(${rotateX}deg) rotateY(${rotateY}deg) translateY(-8px)`});card.addEventListener('pointerleave',()=>{card.style.transform=''})}
document.querySelectorAll('[data-tilt]').forEach(addTilt);updateScrollEffects();
